# Generated by Django 3.2.5 on 2022-01-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
