# Generated by Django 3.2.5 on 2022-01-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
