# Generated by Django 3.2.5 on 2022-01-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
