# Generated by Django 3.2.5 on 2022-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(default='', upload_to='Question peper/pdf'),
        ),
    ]
