# Generated by Django 4.0.2 on 2022-02-25 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_notice_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='pdf',
            field=models.FileField(default='', upload_to='Notice/pdf'),
        ),
    ]
