# Generated by Django 4.0.2 on 2022-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notice_date_notice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
