# Generated by Django 4.0.2 on 2022-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(default='Not Availabe', upload_to='Notice/pdf'),
        ),
    ]
