# Generated by Django 4.0.2 on 2022-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_notice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(null=True, upload_to='Notice/pdf'),
        ),
    ]
