# Generated by Django 4.0.2 on 2022-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_result_alter_notice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
