# Generated by Django 4.0.2 on 2022-03-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_notice_link_alter_notice_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='Notice/pdf'),
        ),
    ]
